### ISSUE TITLE
Error while deploying with Next.js

### ISSUE THREAD

**Issue by qlecler** [gpietro/react-numpad#126]
Hi there !

I've this error while trying to deploy a project using your components with next.js :

```
> Build error occurred
{ ReferenceError: regeneratorRuntime is not defined
    at Object.<anonymous> (/home/anytech/courtier_cc/node_modules/react-numpad/build/elements/TimeView.js:24:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/anytech/courtier_cc/node_modules/react-numpad/build/elements/Calendar.js:26:40)
    at Module._compile (internal/modules/cjs/loader.js:701:30) type: 'ReferenceError', '$error': '$error' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /home/anytech/.nvm/versions/node/v10.15.3/bin/node
Arguments: /home/anytech/.nvm/versions/node/v10.15.3/lib/node_modules/yarn/lib/cli.js run build
Directory: /home/anytech/courtier_cc/packages/landing
Output:
```

Any idea to resolve this?

**Comment by gpietro** [comment]
you need to import the [regenerator-runtime]( https://www.npmjs.com/package/regenerator-runtime)
